### ISSUE TITLE
sample for prediction

### ISSUE THREAD

**Issue by OliveiraNt** [pplonski/keras2cpp#3]
Hi, I'm trying to use your code for use the neural net in cpp and I already have my dumped.nnet but I not completely understood de sample file for prediction and how can I use  images for this, if you don't mind, can you explain me this?

**Comment by pplonski** [comment]
Sure, for example purpose I was using MNIST data which I simply dumped from numpy array to text file. This text file is an input for DataChunk2D - this class is a structure to keep information about input image. For MNIST data each sample has depth equal one - that's why there is 2D in DataChunk name. For images with depth equal 3 there should be added new DataChunk3D class in the code.

**Comment by OliveiraNt** [comment]
Thanks for explain me so fast , I tried to understand this through the python code but I have any knowledge about python yet.
